### ISSUE TITLE
SDK setup requires the project folder and the OS to be on the same drive

### ISSUE THREAD

**Issue by ZenithStar** [rivet-gg/plugin-godot#316]
I'm following [this guide](https://rivet.gg/docs/godot/tutorials/quickstart) with a clean project. After clicking "Setup Rivet Modules", the process hangs on "Running". I assume all this does is generate `rivet.dev.json` and `rivet.json`. "Reload Current Project" unhangs "Running" as "Completed", but the next Setup button does not activate.
![image](https://github.com/user-attachments/assets/86a8e031-4bba-4030-966f-d4292222411b)

Notably, the console outputs.
`Failed to open process 6388: The parameter is incorrect. (0x80070057)`

System Info:
Godot v4.3.stable - Windows 10.0.19045 - GLES3 (Compatibility) - NVIDIA GeForce RTX 2060 (NVIDIA; 32.0.15.6094) - Intel(R) Core(TM) i7-4770K CPU @ 3.50GHz (8 Threads)

**Comment by ZenithStar** [comment]
The issue was caused by this error. I bypassed it by remaking the project on the same drive as the OS, but ideally this shouldn't be required. My OS drive is tiny, and I have several other drives in my machine that I use to house projects.

```
[stderr] Waiting another process is currently modifying this project
[stderr] Editor http://127.0.0.1:15220
[stdout] 
[stdout] ────────
[stdout] 
[stderr] Parse config.ts (users)
[stderr] Parse config.ts (rate_limit)
[stderr] Parse config.ts (tokens)
[stderr] Generate SDK addons/rivet_sdk
[stderr] Building SDK godot
[stderr] 
[stderr] 
[stderr] [UNCAUGHT] Error: The system cannot move the file to a different disk drive. (os error 17): rename 'C:\Users\lpvvn\AppData\Roaming\rivet\projects\rhythm_game_mmo_bde40345444196fc\backend\dev\sdk\godot' -> 'E:\Game Dev\rhythm-game-mmo\addons\rivet_sdk'
[stderr]   at async Object.rename (ext:deno_fs/30_fs.js:274:3)
[stderr]   at async move (https://jsr.io/@std/fs/0.213.1/move.ts:72:3)
[stderr]   at async generateSdk (file:///C:/Users/lpvvn/AppData/Roaming/rivet/backend/5b4c05a00edfb2b7d6888dee94fad225027eb9aa5f6f99f77ab44fc3a2c3e020/toolchain/sdk/generate.ts:74:2)
[stderr]   at async Object.build (file:///C:/Users/lpvvn/AppData/Roaming/rivet/backend/5b4c05a00edfb2b7d6888dee94fad225027eb9aa5f6f99f77ab44fc3a2c3e020/toolchain/build/plan/project.ts:151:6)
[stderr]   at async fn (file:///C:/Users/lpvvn/AppData/Roaming/rivet/backend/5b4c05a00edfb2b7d6888dee94fad225027eb9aa5f6f99f77ab44fc3a2c3e020/toolchain/build_state/mod.ts:144:4)
[stderr]   at async Function.allSettled (<anonymous>)
[stderr]   at async waitForBuildPromises (file:///C:/Users/lpvvn/AppData/Roaming/rivet/backend/5b4c05a00edfb2b7d6888dee94fad225027eb9aa5f6f99f77ab44fc3a2c3e020/toolchain/build_state/mod.ts:181:21)
[stderr]   at async planProjectBuild (file:///C:/Users/lpvvn/AppData/Roaming/rivet/backend/5b4c05a00edfb2b7d6888dee94fad225027eb9aa5f6f99f77ab44fc3a2c3e020/toolchain/build/plan/project.ts:315:2)
[stderr]   at async build (file:///C:/Users/lpvvn/AppData/Roaming/rivet/backend/5b4c05a00edfb2b7d6888dee94fad225027eb9aa5f6f99f77ab44fc3a2c3e020/toolchain/build/mod.ts:66:2)
[stderr]   at async Object.fn (file:///C:/Users/lpvvn/AppData/Roaming/rivet/backend/5b4c05a00edfb2b7d6888dee94fad225027eb9aa5f6f99f77ab44fc3a2c3e020/cli/tasks/dev.ts:57:6)
[stderr] 
[stderr] 
[stderr] Failed. Found 1 error.
```

As a side note, the both the `Game Sever` and `Modules` docks initialize to only one line of height, making this separate console output much harder to find.
